- name: Disable redis
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable Redis 6
  ansible.builtin.shell: dnf module enable redis:6 -y

- name: Install Redis Server
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes