- name: Install golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: App pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: Install dependencies and build software
  ansible.builtin.shell: |
    go mod init dispatch
    go get
    go build
  args:
    chdir: /app

- name: SystemD setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd



